ASSUME CS:CODE, DS:DATA
DATA SEGMENT
    VAL1 DW 0002H
    VAL2 DW 0002H
DATA ENDS
CODE SEGMENT
START:
    MOV AX, DATA
    MOV DS, AX
    MOV AX, VAL1
    MOV BX, VAL2
    ADD AX, BX
    MOV AH, 4CH
    INT 21H
CODE ENDS
END START